<?xml version="1.0" encoding="utf-8"?><Database Name="PFMDatabase" Class="PFMDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TUANNA01030-PC;Initial Catalog=PFMDatabase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PFMDatabaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BorrowingLending" Member="BorrowingLendings">
    <Type Name="BorrowingLending">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DebtType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Money" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="InterestType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InterestRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PersonName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PersonPhone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PersonAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_BorrowingLending" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastSync" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_BorrowingLending" Member="BorrowingLendings" ThisKey="ID" OtherKey="UserID" Type="BorrowingLending" />
      <Association Name="User_Category" Member="Categories" ThisKey="ID" OtherKey="UserID" Type="Category" />
      <Association Name="User_Entry" Member="Entries" ThisKey="ID" OtherKey="UserID" Type="Entry" />
      <Association Name="User_Schedule" Member="Schedules" ThisKey="ID" OtherKey="UserID" Type="Schedule" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserColor" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Category_EntryDetail" Member="EntryDetails" ThisKey="ID,UserID" OtherKey="CategoryID,UserID" Type="EntryDetail" />
      <Association Name="Category_ScheduleDetail" Member="ScheduleDetails" ThisKey="ID,UserID" OtherKey="CategoryID,UserID" Type="ScheduleDetail" />
      <Association Name="User_Category" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Entry" Member="Entries">
    <Type Name="Entry">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Entry_EntryDetail" Member="EntryDetails" ThisKey="ID,UserID" OtherKey="EntryID,UserID" Type="EntryDetail" />
      <Association Name="User_Entry" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EntryDetail" Member="EntryDetails">
    <Type Name="EntryDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Money" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EntryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Entry_EntryDetail" Member="Entry" ThisKey="EntryID,UserID" OtherKey="ID,UserID" Type="Entry" IsForeignKey="true" />
      <Association Name="Category_EntryDetail" Member="Category" ThisKey="CategoryID,UserID" OtherKey="ID,UserID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Budget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Schedule_ScheduleDetail" Member="ScheduleDetails" ThisKey="ID,UserID" OtherKey="ScheduleID,UserID" Type="ScheduleDetail" />
      <Association Name="User_Schedule" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleDetail" Member="ScheduleDetails">
    <Type Name="ScheduleDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Budget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScheduleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Schedule_ScheduleDetail" Member="Schedule" ThisKey="ScheduleID,UserID" OtherKey="ID,UserID" Type="Schedule" IsForeignKey="true" />
      <Association Name="Category_ScheduleDetail" Member="Category" ThisKey="CategoryID,UserID" OtherKey="ID,UserID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>